;;; lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from shaoline.el

(autoload 'shaoline-mode "shaoline-mode" "\
Toggle Shaoline minor mode." t)
(autoload 'shaoline-initialize "shaoline" "\
Initialize Shaoline mode — convenience function." t)
(autoload 'shaoline-show-logs "shaoline" "\
Display the Shaoline debug log buffer." t)
(register-definition-prefixes "shaoline" '("shaoline-"))


;;; Generated autoloads from shaoline-effects.el

(register-definition-prefixes "shaoline-effects" '("shaoline-"))


;;; Generated autoloads from shaoline-mode.el

(defvar shaoline-mode nil "\
Non-nil if Shaoline mode is enabled.
See the `shaoline-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `shaoline-mode'.")
(custom-autoload 'shaoline-mode "shaoline-mode" nil)
(autoload 'shaoline-mode "shaoline-mode" "\
Global minor mode for Shaoline echo-area modeline.

Following the Dao of Wu Wei, Shaoline adapts its behavior based on context:

- yin: Minimal impact, manual updates only
- yang: Active monitoring, always visible
- adaptive: Intelligent switching based on environment

Use \\[shaoline-toggle-strategy] to cycle strategies.
Use \\[shaoline-refresh] to manually update.
Use \\[shaoline-clear] to clear display.

This is a global minor mode.  If called interactively, toggle the
`Shaoline mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='shaoline-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "shaoline-mode" '("shaoline-"))


;;; Generated autoloads from shaoline-segments.el

(register-definition-prefixes "shaoline-segments" '("shaoline-"))


;;; Generated autoloads from shaoline-strategy.el

(register-definition-prefixes "shaoline-strategy" '("shaoline-"))

;;; End of scraped data

(provide 'lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lisp-autoloads.el ends here
